name: Build and Test

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.4

      - name: Give permissions to database directory
        run: chmod -R 777 ./src/database

      - name: Create SQLite database
        run: touch ./src/database/database.sqlite

      - name: Give permissions to SQLite database
        run: chmod -R 777 ./src/database/database.sqlite

      - name: Copy .env.test to .env
        run: cp ./src/.env.test ./src/.env

      - name: Install Composer dependencies
        run: cd src && composer install

      - name: Run Laravel migrations
        run: cd src && php artisan migrate

      - name: Run PHPUnit tests
        run: cd src && ./vendor/bin/phpunit