name: Build and Test

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.4

      - name: Give permissions
        run: chmod -R 777 ./src/database
      - name: Create database
        run: touch ./src/database/database.sqlite
      - name: Give permissions to database
        run: chmod -R 777 ./src/database/database.sqlite

      - name: Copy .env
        run: cp .env.test .env

      - name: Install app
        run: composer install

      - name: Run migrations
        run: php artisan migrate

      - name: Test PHPUnit
        run: ./vendor/bin/phpunit