name: sync-dev-branch

on:
  push:
    branches:
      - dev

jobs:
  sync:
    runs-on: ubuntu-latest

    name: Syncing branches
    steps:
      - name: checkout current working branch
        uses: actions/checkout@v2

      - name: push onto dev branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: git push --force origin HEAD:dev
